using UnityEngine;

public static class LoreEntryConst
{
    public static readonly LoreEntry[] Entries = new LoreEntry[]
    {
        new LoreEntry(1, "I always wanted to see what was at the top. | Do you think I can make it? | Do you think I can prove them wrong?", false),
        new LoreEntry(2, "The mountain is a cruel mistress. | It gives and it takes, and it never forgets those who dare to challenge it.", false),
        new LoreEntry(3, "Everyone in town is excited for the festival. | It's happening on level 2 this year. I can't wait to be there.", true),
        new LoreEntry(4, "This is where my wife proposed to me. | Ahaha. My friends wouldn't let me live it down. | I took too long, so she just did it first.", true),
        new LoreEntry(5, "Today, I'm taking my first step into being a big girl, and it's by climbing my home to the TOP! Let's live this life!", true),
        new LoreEntry(6, "To whoever keeps drawing crude drawings on the walls of MY HOUSE!!! | I hope you know the joke was funny the first time.", true),
        new LoreEntry(7, "Did you know that stones hold a lot of memories? Fossils, imprints in the rocks, maybe sometimes even feelings. | People's strongest feelings here are printed into the rocks and crystals of this place. | You can read them, if you look. I find it so sad. ", false),
        new LoreEntry(8, "This is for my pet dung beetle. You really held me together. I'll try to be strong for you.", false),
        new LoreEntry(9, "This is where my friend lived before she moved in with her husband together. | I wish she hadn't moved. | Perhaps, then, I wouldn't have left this world alone.", true),
        new LoreEntry(10, "I used to always think I was alone. | Head first into the soft rock, this is where I cried all my tears. | The water from my tears created a crevice here.", true),
        new LoreEntry(11, "I miss eating my mom's homemade bread.", false),
        new LoreEntry(12, "I always wanted to be a climber. I wanted to climb the highest peaks and see the world from above. | But now, I just want to rest.", false),
        new LoreEntry(13, "I want to see what the world looks like below, but it's so hard living outside of this mountain, ever since last year. I'm glad we have this mountain.", true),
        new LoreEntry(14, "Halcyonites are pretty sad lately. I need to step forward to help my people, as a leader. | Good thing I went to clown school.", true),
        new LoreEntry(15, "Where are we, mom? Mom? Where are you?", true),
        new LoreEntry(16, "I miss my mom.", true),
        new LoreEntry(17, "Hey, why is it getting so dark all of a sudden?", true),
        new LoreEntry(18, "Don't worry. Keep climbing. You won't fall. You can't fall. The mountain is always here to catch you. We're here.", true),
        new LoreEntry(19, "Someone always used to care.", false),
        new LoreEntry(20, "This stone... Can you see? This is my hand. My hand's been printed in the stone.", true),
        new LoreEntry(21, "You're so... warm...", true),
        new LoreEntry(22, "Thank you for holding my hand.", true),
        new LoreEntry(23, "Hahah. This was the last expression I made. | Scary, right? To be captured in stone like this.", true),
        new LoreEntry(24, "Can you reach the top? | We all have a surprise for you.", true),
        new LoreEntry(25, "I'm sure you guessed it by now, but all those messages in crystals, from earlier. | They were from us. | Can you remember them for us? | Can you carry us to the top?", true),
        new LoreEntry(26, "Can you take us with you? Please?", true),
        new LoreEntry(27, "I wonder what it feels like, being so free.", true),
        new LoreEntry(28, "Hey, take your time. You're in no rush. | It's cool to take a break. | Cool is the way to be lately.", false),
        new LoreEntry(29, "The festival was awesome. I really really really really really liked the bread the made here.", true),
        new LoreEntry(30, "Level 3 really has some eccentric people living in it. I sure won't miss it! ... Well, maybe I will, just a little.", true),
        new LoreEntry(31, "Who does my neighbor think he is? I'll draw as many phalluses as I want.", true),
        new LoreEntry(32, "To whoever keeps drawing phalluses on everyone's home...!! See you in COURT!!!", true),
        new LoreEntry(33, "If a rock breaks as you were holding, don't panic. It really just means this path wasn't meant for you. | It's okay. You can take another one.", false),
        new LoreEntry(34, "Don't worry, you can let go and look around. See this cactus? This giant cactus? | That used to be my favorite thing to look at, early in the morning.", false),
        new LoreEntry(35, "Another adventurer used to climb this mountain like you. They left their stuff for people like you.", false),
        new LoreEntry(36, "Take us with you, yeah?", false),
        new LoreEntry(37, "Please, keep going.", false),
        new LoreEntry(38, "Please, keep fighting.", false),
        new LoreEntry(39, "It's okay. It's okay. I know my child is in safe hands. The mountain will take care of her.", true),
        new LoreEntry(40, "We're in the stone. Can you feel it?", true),
        new LoreEntry(41, "We're waiting for you to reach the top. We have something to show you. I cannot wait.", true),
        new LoreEntry(42, "Yes, we are talking to you.", true),
        new LoreEntry(43, "We're in the stone, in memory, and always with you. Just like the mountain has always been with us.", true),
        new LoreEntry(44, "To whoever keeps drawing phalluses near the top of the mountain... WHY!!!!! STOP IT.", true),
        new LoreEntry(45, "THAT'S WHERE I HIT MY RECORD FOR HIGHEST CLIMB. WOOHOO, AND IT'S SET IN STONE TOO.", false),
        new LoreEntry(46, "I REALLY HOPE NO ONE BEATS MY RECORD AND CLIMBS HIGHER.", false),
        new LoreEntry(47, "Woah, the sky is so pretty.", false),
        new LoreEntry(48, "I used to go down this mountain and travel for KILOMETERS to get water. See that river over there? No? Whatever. Glad I don't need to drink anymore, now that I'm stone.", true),
        new LoreEntry(49, "HMRHPH.", true),
        new LoreEntry(50, "HUHFF. HUHF. HUFH.", true),
        new LoreEntry(51, "SORRY.", true),
        new LoreEntry(52, "The mountain moves for you, you know? If you need to change angles, just push those buttons.", false),
        new LoreEntry(53, "Woah, you're beautiful. No, not you. The view. I meant the view. I'm talking about the view. NOT YOU.", true),
        new LoreEntry(54, "When I looked at the people after that storm, I swore they looked different.", false),
        new LoreEntry(55, "This is where a part of me died.", true),
        new LoreEntry(56, "I don't like looking up anymore. It's staring back at me.", false),
        new LoreEntry(57, "By the dust, by the stone, by my grinding groan~ Each step you take is another call home~", true),
        new LoreEntry(58, "Ascend and relish, relish the halcyon~ That from dusk ‘til dawn, you were never alone.~", true),
        new LoreEntry(59, "^_^ <-- look, it's a smiley face without a smile | c===8 | STOP THAT.", true),
        new LoreEntry(60, "KILNO IS A LOSER | WHOEVER WROTE THIS IS GOING TO COURT!!!", true),
        new LoreEntry(61, "I LOVE MY WIFE | I LOVE YOUR WIFE TOO | BASTARD", true),
        new LoreEntry(62, "THIS MY TABLET NUMBER 44542324345 | Nobody wants you", true),
        new LoreEntry(63, "STOP RAISING PRICE OF SHEEP !!! ", true),
        new LoreEntry(64, "Such unilateral lack of care and management from the leader who is a behaving like such a clown we need to revolt us the people we need to unite and fight as one and reconnect and reclaim and be one alogn with the mountain and also fight for what we have and the joy of perhaps living and seeing another day in the | ... NOBODY is reading all that.", true),
        new LoreEntry(65, "Missing ! Pet bird. About this big | Saw your bird near level 1 | No it's near level 3 | Saw your bird at the top | Can anyone help me find my bird please", true),
        new LoreEntry(66, "HEY EVERYONE FINISH THE SENTENCE. KILNO IS A ____ | Husband | Wife | Loser | Artist drawing on the walls of my house | SO IT WAS YOU?! | No it's not me I'm being set up | STOP WRITING ON THE WALLS!!", true),
        new LoreEntry(67, "Stop erasing my drawings and my tags | Hey your drawings rock by the way | Nobody's touching your drawings. The rain is making the paint fade away | Ooooooooohh that makes sense", true),
        new LoreEntry(68, "Looking for permanent paint for walls | I think they used to have some on level 4", true),
        new LoreEntry(69, "I want to kick the leader into the lava | We don't have lava anymore | We really can't have anything anymore around here", true),
        new LoreEntry(70, "We are creeping way too close to breaking the rules, and then we would all ... everyone, listen to me!!", true),
        new LoreEntry(71, "CAN ANYONE CONFIRM IF LEVEL 5 EXISTS? Asking for a friend || What? you can literally see it. Look up.", true),
        new LoreEntry(72, "This wall used to be clean until KILNO GOT HERE.", true),
        new LoreEntry(73, "Not sorry for what I did. I’d do it again. The mountain remembers who started the bread riot.", true),
        new LoreEntry(74, "I kissed someone here once. Then she left and became mayor. Guess I peaked. hehe. pun.", true),
        new LoreEntry(75, "I’m still not over what happened at last year’s festival.", true),
        new LoreEntry(76, "We all leave something behind. Some leave stories. Some leave scars. I left snacks. Bon appétit.", false),
        new LoreEntry(77, "I’m not climbing anymore. I don't have the strength to.", false),
        new LoreEntry(78, "The stone remembers better than I ever could. Thank goodness.", false),
        new LoreEntry(79, "I only made it this far. That’s okay. This was far enough for me.", false),
        new LoreEntry(80, "Take my handprint. Take my voice. Take my name if you want it. Just... keep going.", true),
        new LoreEntry(81, "One day, someone will reach the top. I hope it's me.", false),
        new LoreEntry(82, "I WAS HERE | Who?", false),
        new LoreEntry(83, "Climbed with one shoe. Still made it farther than you.", false),
        new LoreEntry(84, "Bread. bread. bread. bread. bread. bread. bread.", false),
        new LoreEntry(85, "IF YOU CAN READ THIS, YOU'RE TOO CLOSE TO MY STASH. BACK OFF.", false),
        new LoreEntry(86, "I made it to Level 6! | There's no level 6 idiot | Yes there is || What are you talking about", true),
        new LoreEntry(87, "Draw something beautiful here. | Someone drew a flower | Upon closer inspection, someone drew on top of a crude drawing to make it look like a flower.", false),
        new LoreEntry(88, "WE USED TO SING HERE", true),
        new LoreEntry(89, "This wall is cursed. Touch it if you want weird dreams.", false),
        new LoreEntry(90, "Reminder: you can't fall, you can't roll, and you can't tumble. You're not much a rock yet!", false),
        new LoreEntry(91, "THE WALL IS NOT YOUR DIARY.", false),
        new LoreEntry(92, "I miss my mom. I miss my dad. I miss my friends. I miss the world.", false),
        new LoreEntry(93, "I miss the world too. I miss the people. I miss the stories. I miss the laughter.", false),
    };
}
